# -*- coding: utf-8 -*-
"""week2-agisha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6NszrydrDaZQbr6oPHpV5v_YW0UbKJj

# Import Library
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression

"""# Load Dataset"""

from sklearn.datasets import load_diabetes
diabetes = datasets.load_diabetes()

diabetes

#ada data, target, feature_names

"""# EDA"""

#coba liat terpisah biar ena diliat
X = diabetes.data
Y = diabetes.target

X

Y

#cek X size X object
#442 row 10 columns

#cek Y size 
#442 outputs
print(X.shape)
print(Y.shape)

df = pd.DataFrame(X)

# Feature names datanya niw
diabetes.feature_names

df.columns = diabetes.feature_names
df #liat indexnya berdasarkan feature namesnya

sns.pairplot(df)

# Cek korelasi
sns.heatmap(df.corr())

"""# Split Data"""

from sklearn import model_selection
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y)
# Udh di split ni

print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)
# Print shapenya masing-masing

"""# Create Model"""

# Buat obj reg_agi
reg_agi = linear_model.LinearRegression()

# Training cuy, masukin ke obj reg_agi
reg_agi.fit(X_train, Y_train)

# Buat prediksi ke X_test, nanti di save di Y_pred
Y_pred = reg_agi.predict(X_test)

# Print predicted Valuenya
Y_pred

# Buat perbandingan pake grafik yg scatter cuy

x_line = np.arange(0, 350, 1)
plt.plot(x_line, "r")
plt.scatter(Y_pred, Y_test)

plt.ylabel('Label Asli')
plt.xlabel('Label Prediksi')

plt.grid()
plt.show()